/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp15' at '7/11/19 3:26 PM' with Gradle 3.0
 *
 * @author hp15, @date 7/11/19 3:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
